services:
  spring-app:
    image: spring-app
    container_name: spring-app
    ports:
      - "8081:8081"
    env_file:
      - .env   # Теперь Docker будет подгружать переменные окружения из .env
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: scheduleproject
      POSTGRES_USER: pinkyzeus
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}  # Использование пароля из .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
