version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/scheduleproject
      SPRING_DATASOURCE_USERNAME: pinkyzeus
      SPRING_DATASOURCE_PASSWORD: bdd185-kv114
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: scheduleproject
      POSTGRES_USER: pinkyzeus
      POSTGRES_PASSWORD: bdd185-kv114
    ports:
      - "5432:5432"

  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
    interval: 5m
    timeout: 10s
    retries: 3
