version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/scheduleproject
      - SPRING_DATASOURCE_USERNAME=pinkyzeus
      - SPRING_DATASOURCE_PASSWORD=bdd185-kv114
      - SPRING_MAIL_HOST=smtp.timeweb.ru
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=ksu@24schedule.ru
      - SPRING_MAIL_PASSWORD=95wnqo37s0
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: scheduleproject
      POSTGRES_USER: pinkyzeus
      POSTGRES_PASSWORD: bdd185-kv114
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
