# Конфигурационный файл
server:
  #port: 8081
  #address: 188.225.24.65 # IP адрес сервера
  tomcat:
    remoteip:
      host-header: 24schedule.ru
spring:

  # Подключение к H2 бд через jdbc
  datasource:
    url: jdbc:h2:file:/data/db

  # Включение liquibase и установка основного файла
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

  http:
    multipart:
      enabled: true



connection:
  names:
    - test
    - live
  addresses:
    test: http://localhost:8088
    live: https://24schedule.ru



