# Конфигурационный файл
server:
  port: 8088
spring:

  # Подключение к H2 бд через jdbc
  datasource:
    url: jdbc:h2:mem:testdb

  # Включение liquibase и установка основного файла
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true



