name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Build Docker image
        run: docker build . -t schedule-image

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker tag schedule-image "${{ secrets.DOCKER_HUB_USERNAME }}/schedule-image"
          docker push "${{ secrets.DOCKER_HUB_USERNAME }}/schedule-image"

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa    

      - name: Deploy to remote server
        run: ssh -o StrictHostKeyChecking=no root@77.232.128.111 "docker pull your-docker-image-name && docker-compose up -d"

      - name: Notify Telegram
        run: |
            curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" 
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" 
            -d "text=Сборка завершена!" # Замените текст на нужное сообщение  

      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=Сборка завершилась с ошибкой!"
